/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as CommunitiesCommunityIdChannelsChannelIdRouteImport } from './routes/communities.$communityId.channels.$channelId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCommunityIdChannelsChannelIdRoute =
  CommunitiesCommunityIdChannelsChannelIdRouteImport.update({
    id: '/communities/$communityId/channels/$channelId',
    path: '/communities/$communityId/channels/$channelId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat/$id': typeof ChatIdRoute
  '/communities/$communityId/channels/$channelId': typeof CommunitiesCommunityIdChannelsChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat/$id': typeof ChatIdRoute
  '/communities/$communityId/channels/$channelId': typeof CommunitiesCommunityIdChannelsChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat/$id': typeof ChatIdRoute
  '/communities/$communityId/channels/$channelId': typeof CommunitiesCommunityIdChannelsChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chat/$id'
    | '/communities/$communityId/channels/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat/$id'
    | '/communities/$communityId/channels/$channelId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat/$id'
    | '/communities/$communityId/channels/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatIdRoute: typeof ChatIdRoute
  CommunitiesCommunityIdChannelsChannelIdRoute: typeof CommunitiesCommunityIdChannelsChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$communityId/channels/$channelId': {
      id: '/communities/$communityId/channels/$channelId'
      path: '/communities/$communityId/channels/$channelId'
      fullPath: '/communities/$communityId/channels/$channelId'
      preLoaderRoute: typeof CommunitiesCommunityIdChannelsChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatIdRoute: ChatIdRoute,
  CommunitiesCommunityIdChannelsChannelIdRoute:
    CommunitiesCommunityIdChannelsChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
